#!/usr/bin/python3
"""changelist
A script that lists the objects modified in the pre-link phase.
These objects may then be relinked in vxWorks to reload changes.

Usage:
    changelist FILE
    changelist [--version]
    changelist [-h | --help]

Options:
    -h --help                   Show this screen.
    --version                   Show version.

Adding filters:
    Run this command over a startup script  to obtain the objects needed to be linked at run-time:
        perl -ne \'m|^ld < \/.*\/(.+.o)| && print \"\\"$1\\", \"\' startup-script.cmd 
    The list can then be added to this script.
"""
import sys
import os
import re

try:
    from docopt import docopt
except ImportError:
    exit("This software refuses to run until docopt is installed:\n$ pip install docopt")

def main(args):

    # default configuration
    cfg = {}

    regex = r"Entering directory .+?\/code\/(.*)\'(.|\n)+?ldppc .*-o ([^.]*.o)"

    try:
        filename=args['FILE']
        with open(filename, 'r') as f:
            data=f.read()
    except TypeError as e:
        exit("File not specified")
    except FileNotFoundError as e:
        exit(filename + " not found")
    
    matches = re.finditer(regex, data, re.MULTILINE)

    for matchNum, match in enumerate(matches):
        obj = re.match('([^-]+)(-[^.]+)?(\.o)', match.group(3)).group(1) + '.o'
            
        print(match.group(1) + '/' + match.group(3))
    
if __name__ == '__main__':
    args = docopt(__doc__, version='0.1')
    main(args)


