#!/usr/bin/python3
"""changelist
A script that lists the objects modified in the pre-link phase.
These objects may then be relinked in vxWorks to reload changes.

Usage:
    changelist FILE
    changelist [--version]
    changelist [-h | --help]

Options:
    -h --help                   Show this screen.
    --version                   Show version.
"""
import sys
import os
import re

try:
    from docopt import docopt
except ImportError:
    exit("This software refuses to run until docopt is installed:\n$ pip install docopt")

def main(args):
    regex = r".+?ldppc .*-o ([^.]*.o)(.|\n)+?Leaving directory .+?\/code\/(.*)\'"

    try:
        filename=args['FILE']
        with open(filename, 'r') as f:
            data=f.read()
    except TypeError as e:
        exit("File not specified")
    except FileNotFoundError as e:
        exit(filename + " not found")
    
    matches = re.finditer(regex, data, re.MULTILINE)

    for match in matches:
        print(match.group(3) + '/' + match.group(1))
    
if __name__ == '__main__':
    args = docopt(__doc__, version='0.1')
    main(args)


