#!/bin/bash

f_usage()
{
   echo " Usage  : `basename $0` sun | linux"
   echo "          `basename $0` clean"
}

f_checkmakefile()
{
	makefile=$1
	if grep --quiet "NP_SOFT" $makefile; then
		return 0
	else
		return -1 
	fi
}

f_initial()
{
    target=$1

	makefiles=($(find . -mindepth 2 -name "Makefile"))
	#for i in ${makefiles[@]}; do
	#	if ! f_checkmakefile $i; then
	#		echo "Weird $i. Please fix it."
	#		exit 0
	#	fi
	#done

	echo -n "Creating backups of the original sun-specific Makefiles ..."
	for i in ${makefiles[@]}; do 
		cp -a $i  $i.sun
	done
	echo " done"

	echo -n "Creating linux-specific Makefiles ........................."
	for i in ${makefiles[@]}; do 
		cp $i $i.linux
		perl -pi -e 's#NP_SOFT\s:sh=\secho.*#NP_SOFT := \$(shell echo `pwd | sed -n \"s/\\/code\\// /p\"` \$NP_SOFT | cut -d" " -f1 )#' $i.linux
		perl -pi -e "s/-g -mcpu=604/-mcpu=604/" $i.linux # remove debugging symbols	
		#perl -pi -e "s/CFLAGS =( -O)? -Wall -Werror/CFLAGS = -O -Wno-endif-labels -Wno-packed -Wno-overflow/" $i.linux
		perl -pi -e "s/CFLAGS =( -O)? -Wall -Werror/CFLAGS = -O -Wall -Werror -DWIND_RIVER_C=-1/" $i.linux
	done
	echo " done"
}

if [ $# -ne "1" ]
then
    f_usage
else
    target=$1

    if [ $target == sun -o $target == linux ]
    then
		makefiles=($(find . -mindepth 2 -name "Makefile.$target"))
		if [ ${#makefiles[@]} -eq 0 ]; then
			makefiles=($(find . -mindepth 2 -name "Makefile"))
			if [ ${#makefiles[@]} -eq 0 ]; then
				echo "No Makefile found; are you in the right directory?"
				echo $(pwd)
				exit 0
			else
				f_initial $target
			fi
		fi
		
		makefiles=($(find . -mindepth 2 -name "Makefile.$target"))
		echo -n "Creating symlinks towards $target-specific Makefiles ........."
        for i in ${makefiles[@]}; do
            ( cd $(dirname $i);  rm -f Makefile;  ln -s Makefile.$target Makefile )
        done
		echo " done"
    elif [ $target == clean ]
    then
        makefiles=($(find . -mindepth 2 -name "Makefile.sun"))
		if [ ${#makefiles[@]} -eq 0 ]; then
            echo "Nothing to do"
			exit 0
		else
			echo -n "Restoring original Makefiles..."
        
			for i in ${makefiles[@]}; do
				Makefile="$(dirname $i)/$(basename $i .sun)"
				rm -f $Makefile
				mv $i  $Makefile
				[ -f ${Makefile}.linux ] && rm -f ${Makefile}.linux
			done
			echo " Done."
		fi
    else
        f_usage
    fi
fi



